# db/executor.py
from database.queries import execute_custom_query

def execute_llm_query(query):
    """
    Executes the SQL query generated by the LLM.
    
    Args:
        query (str): The SQL query to execute.
    
    Returns:
        list: The result of the executed query.
    """
    result = execute_custom_query(query)
    return result
